services:
  postgres:
    image: postgres:17
    container_name: booksonthetable_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: booksonthetable
      POSTGRES_PASSWORD: booksonthetable
      POSTGRES_DB: booksonthetable

    ports:
      - "5432:5432"

    volumes:
     - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: